<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import IndexPosts from '$lib/components/index_posts.svelte';
  import { postsShow } from '$stores/posts';
  import { onMount } from 'svelte';

  onMount(() => {
    postsShow.filter((post) => !post.tags.includes('writeup'));
  });
</script>

<IndexPosts />