<!-- auto-generated by QWER -->
<script lang="ts">
  import IndexPosts from '$lib/components/index_posts.svelte';
  import { postsShow } from '$stores/posts';
  import { onMount } from 'svelte';

  onMount(() => {
    postsShow.filter((post) => post.tags.includes('writeup'));
  });
</script>

<IndexPosts />